version: "3"

services:
  django:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    network_mode: host # This should be temporary
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: host # This should be temporary

  celery:
    build: .
    command: celery -A CS_Skin_Analytics_Django worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
    network_mode: host # This should be temporary
