# Generated by Django 5.0.3 on 2024-03-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buff163',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash_name', models.CharField(max_length=100)),
                ('buy_max_price', models.FloatField(null=True)),
                ('buy_num', models.IntegerField(null=True)),
                ('can_bargain', models.BooleanField(null=True)),
                ('market_min_price', models.IntegerField(null=True)),
                ('quick_price', models.FloatField(null=True)),
                ('sell_min_price', models.FloatField(null=True)),
                ('sell_num', models.FloatField(null=True)),
                ('sell_reference_price', models.FloatField(null=True)),
                ('transacted_num', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='skinout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash_name', models.CharField(max_length=100)),
                ('float', models.FloatField(null=True)),
                ('stickers', models.JSONField(null=True)),
                ('price', models.FloatField(null=True)),
                ('locked', models.BooleanField(null=True)),
                ('unlock_time', models.CharField(max_length=20, null=True)),
                ('total_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='skinport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash_name', models.CharField(max_length=100)),
                ('suggested_price', models.FloatField(null=True)),
                ('min_price', models.FloatField(null=True)),
                ('max_price', models.FloatField(null=True)),
                ('mean_price', models.FloatField(null=True)),
                ('median_price', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='steam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_name', models.CharField(max_length=100)),
                ('sell_listings', models.IntegerField(null=True)),
                ('sell_price', models.IntegerField(null=True)),
                ('sale_price_text', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
