# Generated by Django 5.0.3 on 2024-06-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0002_personalmarketdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buff163',
            table='buff163_data',
        ),
        migrations.AlterModelTable(
            name='skinout',
            table='skinout_data',
        ),
        migrations.AlterModelTable(
            name='skinport',
            table='skinport_data',
        ),
        migrations.AlterModelTable(
            name='steam',
            table='steam_data',
        ),
    ]
