# Generated by Django 5.0.3 on 2024-06-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0004_buff163_buff_custom_id_skinout_skinout_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buff163',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
