# Generated by Django 5.0.3 on 2024-06-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0005_alter_buff163_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinport',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
