# Generated by Django 5.0.3 on 2024-06-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0009_alter_skinport_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buff163',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skinout',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skinport',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='steam',
            options={'managed': False},
        ),
    ]
